### ISSUE TITLE
Add project readme file

### ISSUE THREAD

**Issue by odv** [jscraft-org/lrep#2]
File should contain the following:

- [x] What is this tool for
- [x] How to setup the tool
- [x] How to use it
- [x] Additional debugging notes
- [x] Features/Suggestions guidelines

**Comment by serge-nikitin** [comment]
readme.md looks cool
plz update description for repo, now it's empty

**Comment by serge-nikitin** [comment]
btw. There's an interesting question. Why does everyone use `README.md` file? I've never seen just `readme.md` files, only I use such name. Is there any popular repo with lowercase? Please try to search why they use capslock. Maybe we are wrong with lowercase and it's a problem.

**Comment by odv** [comment]
@serge-nikitin  I don't have any 'Edit' button for the repositories you've invited me to. I think this is because only the repository creator can change the description and topics. Not sure if you have any 'permission' settings that you can check in order to allow me to do things like that in the repos that you create. Let me know.

As for ```README.md``` I did some research. It mostly has to do with the visual strikingness of using all-caps. So in other words, you have a bigger chance of capturing the attention of a user with caps than with lowercase letters. Besides that, UNIX systems would sort capitals before lower case letters, conveniently putting the README before the rest of the directory's content(no longer the case right now). To sum up, it's just to grab the attention of a user.

What's even more interesting is that when you create a repository on Github, you can initialize it with an empty ```README.md``` file so that you can easily clone it on your machine. They seem to use the same naming convention(uppercase)
![readme](https://user-images.githubusercontent.com/5067625/30733921-b7b5eeee-9f81-11e7-9a10-f6d1517b3e20.jpg)

**Comment by serge-nikitin** [comment]
Thanks for researching about README.md. I think that `UNIX systems would sort capitals before lower case letters` is a good point. So, let's do as other do it. But now we know the reason :)

I don't know how to give you access to `edit` button for description for github repos. Please write this description text for lrep and for jscraf.org repos and I'll update it.

**Comment by odv** [comment]
@serge-nikitin Upon researching this more, it seems that only the repository creator is able to edit it. You can actually allow others to do that.
I would go with this description:
``` Utility tool for repository based learning.```
